defaults:
  - _pipeline
  - _self_

etl_metadata.pipeline_name: "preprocess"

# Global pipeline parameters:
# 1. Code modifiers will be used as adjoining parts of the `code` columns during group-bys and eventual
#    tokenization.
code_modifiers: ???

# Pipeline Structure
stages:
  - filter_subjects
  - add_time_derived_measurements
  - preliminary_counts
  - filter_measurements
  - fit_outlier_detection
  - occlude_outliers
  - fit_normalization
  - fit_vocabulary_indices
  - normalization
