etl_metadata.pipeline_name: "preprocess"

code_modifiers: ???

# Pipeline Structure
stages:
  - filter_subjects
  - add_time_derived_measurements
  - preliminary_counts
  - filter_measurements
  - fit_outlier_detection
  - occlude_outliers
  - fit_normalization
  - fit_vocabulary_indices
  - normalization
