input_dir: ${oc.env:AUMC_RAW_DIR}
cohort_dir: ${oc.env:AUMC_PRE_MEDS_DIR}

log_dir: ${cohort_dir}/.logs

# Hydra
hydra:
  job:
    name: pre_MEDS_${now:%Y-%m-%d_%H-%M-%S}
  run:
    dir: ${log_dir}
  sweep:
    dir: ${log_dir}
