admissions:
  offset_col:
    - "admittedat"
    - "dischargedat"
  pseudotime_col:
    - "admittedattime"
    - "dischargedattime"
  output_data_cols:
    - "location"
    - "urgency"
    - "origin"
    - "destination"
    - "weightgroup"
    - "weightsource"
    - "heightgroup"
    - "heightsource"
    - "specialty"

numericitems:
  offset_col:
    - "measuredat"
    - "registeredat"
    - "updatedat"
  pseudotime_col:
    - "measuredattime"
    - "registeredattime"
    - "updatedattime"
  output_data_cols:
    - "item"
    - "value"
    - "unit"
    - "registeredby"
    - "updatedby"
  warning_items:
    - "How should we deal with `registeredat` and `updatedat`?"

listitems:
  offset_col:
    - "measuredat"
    - "registeredat"
    - "updatedat"
  pseudotime_col:
    - "measuredattime"
    - "registeredattime"
    - "updatedattime"
  output_data_cols:
    - "item"
    - "value"
    - "islabresult"
    - "registeredby"
    - "updatedby"
  warning_items:
    - "How should we deal with `registeredat` and `updatedat`?"

freetextitems:
  offset_col:
    - "measuredat"
    - "registeredat"
    - "updatedat"
  pseudotime_col:
    - "measuredattime"
    - "registeredattime"
    - "updatedattime"
  output_data_cols:
    - "item"
    - "value"
    - "comment"
    - "islabresult"
    - "registeredby"
    - "updatedby"
  warning_items:
    - "How should we deal with `registeredat` and `updatedat`?"

drugitems:
  offset_col:
    - "start"
    - "stop"
  pseudotime_col:
    - "starttime"
    - "stoptime"
  output_data_cols:
    - "orderid"
    - "ordercategory"
    - "item"
    - "rate"
    - "rateunit"
    - "ratetimeunitid"
    - "dose"
    - "doseunit"
    - "doserateunit"
    - "duration"
    - "administered"
    - "administeredunit"
    - "action"
  warning_items:
    - "We **IGNORE** several flags here -- this may be a mistake!"
    - "When is the administered dose recorded? Is this done after the fact?"

procedureorderitems:
  offset_col: "registeredat"
  pseudotime_col: "registeredattime"
  output_data_cols:
    - "orderid"
    - "ordercategoryname"
    - "item"
    - "registeredby"

processitems:
  offset_col:
    - "start"
    - "stop"
  pseudotime_col:
    - "starttime"
    - "stoptime"
  output_data_cols:
    - "item"
